spring:
  datasource:
    url: jdbc:postgresql://ec2-18-210-51-239.compute-1.amazonaws.com:5432/d24igj7ufocdif
    username: ahyrxntwvzdtxp
    password: 956dc1e96936a9ed7eddf193c3e51cf521b145dd5bc15cdf0fabcae2aed7d5ef

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 519435970083-r9oa6c8hnft92eb0sanoqvrp5fnp06j0.apps.googleusercontent.com
            clientSecret: zI11pSBVj70_BldRbmqwMzjt
            redirectUri: "https://murmuring-spire-39725.herokuapp.com/oauth2/callback/google"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBCl
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect